Add vs_lsmash chunk method for mkv/mp4/m2ts
master-of-zen/Av1an pull request #179
Opened 2020-10-13 13:22 UTC by wwww-wwww

now it can be the recommended method

2020-10-13 14:38 UTC, master-of-zen approved these changes

2020-10-13 20:38 UTC, n9Mtq4 commented
@wwww-wwww Did you test this on Windows or a Unix based OS?

2020-10-13 20:49 UTC, n9Mtq4 requested changes

2020-10-13 20:49 UTC, n9Mtq4 commented on Chunks/chunk_queue.py
> +def create_video_queue_vs(args: Args, split_locations: List[int], script: List[str]) -> List[Chunk]:
```suggestion
def create_video_queue_vs(args: Args, split_locations: List[int], script: str) -> List[Chunk]:
```

Can you also add the script param to the docstring for this function?

2020-10-14 01:33 UTC, n9Mtq4 requested changes

2020-10-14 01:33 UTC, n9Mtq4 commented on Startup/setup.py
> +        except:
```suggestion
        except ModuleNotFoundError:
```
This is to address [PEP 8: E722](https://www.flake8rules.com/rules/E722.html).

2020-10-14 16:38 UTC, luigi311 commented
Perhaps we should start adding tests to the workflow when new features are added. I need to add more tests for other encoders so if @wwww-wwww doesnt want to add it on this PR i will add it when i get around to the other encoders.

2020-10-14 18:55 UTC, master-of-zen commented
@wwww-wwww :1st_place_medal:

2020-10-14 18:55 UTC, merged